version: '2'
services:
  backend:
    image: pakoo/ytdl:latest
    environment:
      - USERNAMES=user1,user2
      - BOT_TOKEN=xxxxxxxxxxxxxxxxxxxxx
      - BASE_URL=https://yourserver.com:9000
      - PORT=80
    restart: always
    volumes:
      - ./dl:/app/dl
    ports:
      - 9000:80